# frozen_string_literal: true

# Homebrew formula for agentop.
# This file is generated by scripts/render-homebrew-formula.sh on every release.
# Do not edit by hand — edit the template, not the output.

class Agentop < Formula
  desc "TUI process inspector for Claude Code and OpenAI Codex CLI"
  homepage "https://github.com/leboiko/claude-codex-pid-inspector"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/leboiko/claude-codex-pid-inspector/releases/download/v1.0.0/agentop-1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "e95c5ce8119b9eb9cc910717e5d6f2add3b26d7a93cbfcf8ebadd93841263eb6"
    end
    on_intel do
      url "https://github.com/leboiko/claude-codex-pid-inspector/releases/download/v1.0.0/agentop-1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "3e4da597bbe2f2a3bac226d673f63e7900640d7b45694c6efefc9e870475c55c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/leboiko/claude-codex-pid-inspector/releases/download/v1.0.0/agentop-1.0.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "18f82221920443cef1d62b711ba88bc0525301acb178905bc350ac14145070c2"
    end
    on_intel do
      url "https://github.com/leboiko/claude-codex-pid-inspector/releases/download/v1.0.0/agentop-1.0.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1efbe8f3aa5f47735a6f79c874e599c66e979815aaa87e0688300b80bdec84f4"
    end
  end

  def install
    bin.install "agentop"
  end

  test do
    assert_match "agentop #{version}", shell_output("#{bin}/agentop --version")
  end
end
