# frozen_string_literal: true

# Homebrew formula for markdown-reader (the `markdown-tui-explorer` crate's
# binary). Generated by scripts/render-homebrew-formula.sh on every release.
# Do not edit by hand — edit the template, not the output.

class MarkdownReader < Formula
  desc "Terminal-based markdown viewer with mermaid rendering, syntax highlighting, and live reload"
  homepage "https://github.com/leboiko/markdown-reader"
  version "1.29.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/leboiko/markdown-reader/releases/download/v1.29.1/markdown-reader-1.29.1-aarch64-apple-darwin.tar.gz"
      sha256 "a2eab7eaf23dc96019a2b8f50dd8e0f7f7b49adc07f5e1995c5cb72ad8fcf457"
    end
    on_intel do
      url "https://github.com/leboiko/markdown-reader/releases/download/v1.29.1/markdown-reader-1.29.1-x86_64-apple-darwin.tar.gz"
      sha256 "e61833895d26ba2a7c5af50d0559db64d1e713662d37ff17cf9b3e36259650ab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/leboiko/markdown-reader/releases/download/v1.29.1/markdown-reader-1.29.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2a8e92107013bdea212d9d83fa1f2cb7ebb4d32cb4f77cd0e96306a832c25435"
    end
    on_intel do
      url "https://github.com/leboiko/markdown-reader/releases/download/v1.29.1/markdown-reader-1.29.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "090093aa2712cef869d3f76b3c9c8b6d8fca490d75307b54d0f8cd91876a3a23"
    end
  end

  def install
    bin.install "markdown-reader"
  end

  test do
    assert_match "markdown-reader", shell_output("#{bin}/markdown-reader --help")
  end
end
